export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_CATEGORY= "FILTER_PRODUCTS_BY_CATEGORY";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_SAVE_FACTURACION ="CART_SAVE_FACTURACION";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";

export const PRODUCT_DETAILS_REQUEST ="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL ="PRODUCT_DETAILS_FAIL";

export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FILTER_PROJECTS_BY_PLAN = "FILTER_PROJECTS_BY_PLAN";

export const FETCH_VIDEOS = "FETCH_VIDEOS";


export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const FETCH_ARTICULOS = "FETCH_ARTICULOS";

export const ORDER_CREATE_REQUEST ="ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL ="ORDER_CREATE_FAIL";
export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL ="ORDER_DETAILS_FAIL";
export const ORDER_PAY_REQUEST ="ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL ="ORDER_PAY_FAIL";
export const MY_ORDER_LIST_REQUEST ="MY_ORDER_LIST_REQUEST";
export const MY_ORDER_LIST_SUCCESS="MY_ORDER_LIST_SUCCESS";
export const MY_ORDER_LIST_FAIL="MY_ORDER_LIST_FAIL";
export const ORDER_DELETE_REQUEST="ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS="ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL="ORDER_DELETE_FAIL";
export const ORDER_LIST_REQUEST ="ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS ="ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL ="ORDER_LIST_FAIL";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ESTADISTICAS = "FETCH_ESTADISTICAS";


